name: Deploy Vue and Django Apps

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js for Vue app
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Use Node.js 20

    # Install Vue app dependencies
    - name: Install dependencies for Vue app
      run: |
        cd bus-frontend
        npm install

    # Build Vue app
    - name: Build Vue app
      run: |
        cd bus-frontend
        npm run build

    # Set up Python for Django app
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    # Write the .env file using GitHub Secrets
    - name: Write .env file
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> /var/www/dgpbus/dgp_bus/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> /var/www/dgpbus/dgp_bus/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> /var/www/dgpbus/dgp_bus/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /var/www/dgpbus/dgp_bus/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> /var/www/dgpbus/dgp_bus/.env

    # Install Django dependencies
    - name: Install dependencies for Django app
      run: |
        cd dgp_bus
        pip install -r requirements.txt

    # Run Django migrations
    - name: Apply Django migrations
      run: |
        cd dgp_bus
        python manage.py migrate

    # Collect Django static files
    - name: Collect static files for Django
      run: |
        cd dgp_bus
        python manage.py collectstatic --noinput

    # Deploy to the server
    - name: Deploy to Droplet via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /var/www
          git pull origin main
          source venv/bin/activate
          
          cd dgp_bus && python manage.py migrate
          cd dgp_bus && python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          
          cd bus-frontend && npm run build
          sudo cp -R /var/www/bus-frontend/dist/* /var/www/html/
          sudo systemctl restart nginx

