name: Deploy Vue and Django Apps

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js for Vue app (local to the GitHub runner)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Install Vue app dependencies (on the GitHub runner)
    - name: Install dependencies for Vue app
      run: |
        cd bus-frontend
        npm install

    # Build Vue app (on the GitHub runner)
    - name: Build Vue app
      run: |
        cd bus-frontend
        npm run build

    # Set up Python for Django app (on the GitHub runner)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    # SSH into your droplet to deploy (remote execution)
    - name: Deploy to Droplet via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /var/www/dgpbus  # On the remote droplet
          git pull origin main  # Pull the latest changes
          cd /var/www/dgpbus/dgp_bus
          python3 -m venv venv
          source /var/www/dgpbus/dgp_bus/venv/bin/activate  # Activate the virtual environment on the droplet
          
          # cp env file
          cp /home/peter/envs/backend/.env /var/www/dgpbus/dgp_bus/.env

          # Django backend deployment
          cd /var/www/dgpbus/dgp_bus && python3 manage.py migrate
          cd /var/www/dgpbus/dgp_bus && python3 manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          
          # Build Vue app on the droplet
          cd /var/www/dgpbus/bus-frontend && npm run build
          sudo cp -R /var/www/dgpbus/bus-frontend/dist/* /var/www/html/
          sudo systemctl restart nginx

